[features]
seeds = false
skip-lint = false

[programs.devnet]
tic_world = "FTUi8srvZA5Gng8sfiDFsdN352ydQPnUABWvVqp5qGqF"

[programs.mainnet]
tic_world = "FTUi8srvZA5Gng8sfiDFsdN352ydQPnUABWvVqp5qGqF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[toolchain]
anchor_version = "0.31.1"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
